quarkus.application.name=checkout-service

quarkus.http.port=8083
quarkus.http.host=localhost

kafka.bootstrap.servers=localhost:9092

quarkus.rest-client.order-processing-api.url=http://localhost:8082

quarkus.smallrye-openapi.path=/q/openapi
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=BearerAuth
quarkus.swagger-ui.always-include=true
